services:
  web: 
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules
    environment:
      - NODE_ENV=development
  web-test:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "test:run"]